dist: trusty
language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
services:
- docker
addons:
  sonarcloud:
    organization: grillo-api
    token:
      secure: e4lBUlGak6y7L+mYYIH9VvdulpjPWXmmx+RS17vEKwmjRr+kzKbdZEgkXU3QxNg7X2R2CyQ1UCr45wqRnJandkvW0jhg9EmwvLQsK3/V2DeJIyMHF7mpxNJPrG8YiOJXcIFkM2yBIfhshCfWGfeO8hlX+N0AAAIiPrPtzRU5I+9R0LXAGSAXJwYTmLM6yjNYB3ZZIvq4qi+F5O/kkGS+PxoWWE3+djNrVO6SZh6/D61WridwEnSrsbg/aacdJyo57vNvPW5AT2fwpy2xg6GtCVw1LDPZ8Y7JDub12F/UQnTKXTXZh3OYb17LuY62jTUpc8LGyaQJjGxIsmMluUMYAROiDVVaElU8ROSfEb5HxCnlu6Ogn2qqsmXCNVDMdTpvRqaAxeyrfxUm5LU3fngwEasivNB8D38UaNNzAPQJLc4aycp74T4brTBrwFBLzePv9/4kMyQ+se4LNNyDuCP0+KYjhBmlZZDRRcjuPnNtIa9wtRSZx80ignu0DBlKv4lftZfOyKkBd6S2sOXVgIE3oaJmb9I8ICbTpz8XUWx1xkGTkOZR0REUGExYAGRWFBRPu9zly+53kaXGamGmQS8wNhpor5b5mGczqU9B0WtWl0QE07f39FbHySPjYUNN1SI34jiYjw/vAtORGpzNQTSPqOQqRl28erhrcw9jKbKIJL4=
stages:
- name: Init
- name: Uni Tests
- name: Static Analysis
- name: Build Docker Image
- name: Set Tag
- name: Deploy
before_install:
- chmod +x mvnw
jobs:
  include:
  - stage: Init
    script:
    - echo "##################### INIT - $TRAVIS_REPO_SLUG"
    - echo "BRANCH - $TRAVIS_BRANCH"
    - echo "COMMIT - $TRAVIS_COMMIT"
    - echo "TAG - $TRAVIS_TAG"
    - echo $TRAVIS_BUILD_NUMBER
  - stage: Uni Tests
    name: "Unit Tests"
    script:
    - echo "##################### Executing Unit Test"
    - "./mvnw test"
  - stage: Static Analysis
    script:
    - echo "##################### Executing Sonar"
    - bash <(curl -s https://codecov.io/bash)
    - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
      -Dsonar.projectKey=fernando-lomonaco_grillo-api"
  - stage: Build Docker Image
    if: branch = main
    script:
    - echo "##################### Building docker image"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull adoptopenjdk/openjdk11:alpine-jre
    - "./mvnw deploy jib:build -P deploy-docker -DskipTests"
  - stage: Set Tag
    if: branch = main
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "fernando-lomonaco"
      - git config --local user.email "fernando_lomonaco@outlook.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - echo "##################### Setting tag $TRAVIS_TAG"
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key:
        secure: DTsK886/nRjAFa2p0xae6XylpNKrzy8lharRJxxzzmTTt8V05v44/0hRRp/oJp2ggAUWWzx4wyq67Yo8qxOHL9Lxfhq8k3aI0qT6uoqx6Px3tqNlGiL0ZcJCWQm6gEHBErJhtBNn8FOC98OSgCC/aGVUhbgXTWTRkXxtlr9Q979MXi7dB95NWGC8k0sAVOhQdlmD1LPjnEAhfoBTRkESHVrLXgS42HlOdbeyfSBw4hETNuR422z695JGTiOYRkXf7mqRgyc2AHLh4YZqU1jSVzo8FdOVgcfYnPiKku0C3NqPs3RXVosSN5tc5ZO/9mKuwHei3HS8/kIe/vj/8W+oF4TMaQja2fVCMnw94ZIu0hrqcpAHfZfg5TFx3pviyCIZNVd805U23jUiLoGEvPmztQ5FlNEImnSer1I86KiUy5yrlNKDg4EWPyk6gzL0ylT/uCtkxFgOzo2+qjeZn/rZOEFwpUZRQZMWCjuxYmc1iLy+9v0h8SFzHmvDNTsejra7XlYOMnqHlEOOi7u8dFDelVCtd43BpskI8DizBYWU/2j1itzggaMXtDO+yAZMCFjG5tOJXiI4u2VQjKTR3mRciP2TdhTONuWYyABYMWVKP6gyJ1VNWZWGz7/EgQZ0+djKH5KWzIM0pqTm40ljhHhYUxtnKfS7Kl29w/O6UgKkKEc=
      skip_cleanup: true
  - stage: Deploy
    if: branch = main
    script:
    - echo "##################### Preparando deploy"
    deploy:
      provider: heroku
      api_key:
        secure: my9WwA1y8GMLR/L1RqR1/+PTtdpbH7PENI14Ba/PXC6pLY3NccWtXNZhIolQs27f1CWw4vTpTPu2Gcd68jQatR17dNV7yZYs9O2sXHOGl/MyKIOYo5goywhWzQ3Jpo83n0akOb7raJwlXQwQeMUIfiiHLWbDvVh9+bE6QCDi9qk7YD5brj+ZczyqTsjwJDKAeujfMnwHV8zDU7mHWD8EPwTmIa2YDtIun3bxVh0yvTyPjHCIEyUwCjQhKxXT/vLw55qcdO5e3r+wXQDmtOPlGSGX4cWF43rStxJowFNJh6Uhi/WpUDhzHBIU+VBD/vpOCO+5u944o+GsSKoIj92NuZ6GEbb6VhGEA0q88398r9PMx6l+IoNxaew/u1Ry8y7rNSNlr1xPTt86faYnLcYQeyPvMrbGTiwVsa/VPPAOTf50p6O1XSppGFUGqsJmKKkxBSXTzMxFAeXC0i+8T8gyGM/IPBoGpjc6ciOxzkaGTV7vbxpbsjsNHEoTrI4SxpYaF7/A8j5JS7ZATwbsMF9dfCBB7KeL8tfEJRHmmsAxnJq5tMLgbuOfooPxZlXdZxcfZOIEiO9Vik5Duo6TuGtbVU0kHg3bxkh1+Ac0C9KwERfcNtQwKeVv6n5bwWPQB0taxdoIbOXgpfO+7EN2ifJe/JFnZTmwoS2+dgi5Vg+KUEs=
      app: grillo-api
      edge: true
      on:
        branch: main
notifications:
  email: false
  slack:
  - rooms:
    - secure: JJS7EMIoZQfwnrfy+ozM6kr4t7Ic6cTotRQ/k7GBdueh0ejvl0seKgTCfGVYLZLSUVhCexCpT6mJbFN3eF4BmAj0PUdnyXO/+lrk2vjlfthFl7W0YOCGxSR0UJUJS7x8yBaxkcvE83O+wzS6mUMzB3ys/6vpypxku0dMOJZQVuD1KsK3P4sDsttXTwvz8SpOF2oRAhUDBcxjY6i9/5l/+cBmn5TjEN+ApQPvpVUEd4mXYd34yBx/TZRel3vsnc0tqW2xPxSgQPct2D0jPksavLWiNWaWINyf8VzNurAmmvRGmMNd3Ib3I89/u+nvKSnXetG8ZxKsfSw4CjkMg0VYWkn+cRGYy6yqMp51e6/0VIRXjey1GDdRKIytlwo+r5cCcAU1wMROm+LZkweGw4XkOINAcPQsoaFPVNxfjt1eR4FfDHEkKkgY/WTJ62aWUq5vNiz7GZ5Y63C0qKk/B5z6REJKpluf8LK7+cmZSYRc/rk8Bag9peDxTlcUOGlhFzWYuLtzgFLV1SNSuc31rSlk1InKErD/MrytOtbFJ6hzQcyb50eeGaOqc/pVfCPCZA/3wZpYVxU/oUvvi0aOsMwV5UIdYu+tuaH0FIreT88KfbjsjXvsJ6n5WBMiAwOJ8ZqgxR07AafotMQ2xdIJf0amjm5N6mMmSKvoC+qo9krDpXY=
    on_success: always
    on_failure: never
    template:
    - 'Yeahhhhhh!!! :sunglasses:'
    - 'Build number: #%{build_number}'
    - 'Repository: `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
      for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.'
    - 'Execution time: *%{duration}*'
    - 'Author: %{author}'
    - 'Message: %{message} Mr. Developer'
  - rooms:
    - secure: O6U/iUtjR93mPjOHnC9YttHFs6TqVCmJ1/aJ/ono62gtOWPVPrFJJLbAC0SpmOHBFunJq6OmoQPNrfZ8STOOBuSJB711j1ZkVoBT9cLcSHpU9Et8Be8JzYEYGJ/xYovZZO0FOjYtFlXf84oBNAHvi1QGWlhrgy+EywZopFwR6juyxWRwUqOfNTUR8m5/HbJ/9cec6llBaHlvPa0jC8BW0KfvArwNr+4hFJ84yOTykRCvAqlT75M9f/tiNugwekRfrAfXkKGN69YsTZutU2TaB4H5PxYHqjVZf3UK5EnsfNbe98Ocww7NKg58ft/mTNo3NyyKxWUAnLK58wTXE0bBGvj8lQ1dwcJ9Vxkdwhtit6sOO9qShnDVkzJyunyYPbfsdH5DvqDvC/GgGSUFM5dXPEx1tixH2lEmCD6hlDE5zuAIueuozOY/oEZ1bYhjBo1IpQmsj/tiGPynjLyvmFvwdkdFxX0e7Jp925JnW0AK9AxV90rS1OTgD/pTh6iMMAoEZyD5/v+4hrHNFhxDtIw7Jy+Nc3zf+RaOtu1vZ/x2hfx6ngaGqJC/lqLdOBYXdNBvHmbUadDixT/bg+ZxTq8bybWyV3Ll//7aHw0GE770EZYCK92RT7/9WVQmYGNc2cybmjxh6U7xgxA/x84V098oMxjllfeWsmdtfF0BXO7kVQo=
    on_success: never
    on_failure: always
    template:
    - 'Build number: #%{build_number}'
    - 'Repository: `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
      for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.'
    - 'Execution time: *%{duration}*'
    - 'Author: %{author}'
    - 'Message: %{message} Pay attention Mr. Developer :thinking_face:'